src/Lzdv/InitCmsPostBundle/Entity/PostsListViewInterface.php
<?php

namespace Lzdv\InitCmsPostBundle\Entity;

use Networking\InitCmsBundle\Model\ContentInterface;
use Ibrows\Bundle\SonataAdminAnnotationBundle\Annotation as Sonata;

/**
 * Networking\CategoryBundle\Entity\CategoryViewInterface
 *
 */
interface PostsListViewInterface extends ContentInterface
{
    /**
     * @param  \Application\Sonata\ClassificationBundle\Entity\Collection $media
     * @return $this
     */
    public function setCollection($media);

    /**
     * @return \Application\Sonata\ClassificationBundle\Entity\Collection
     */
    public function getCollection();

    /**
     * @param  string $media
     * @return $this
     */
    public function setText($text);

    /**
     * @return string
     */
    public function getText();

    /**
     * Set createdAt
     *
     * @return $this
     */
    public function setCreatedAt();

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt();

    /**
     * Set updatedAt
     *
     * @param  \DateTime $updatedAt
     * @return $this
     */
    public function setUpdatedAt($updatedAt);

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt();

}

src/Lzdv/InitCmsPostBundle/Resources/views/PostDetailsView/macro.html.twig
{% macro post_details(postDetailsView) %}
    <header class="filters">
        {% if postDetailsView.title %}
            <h1>{{ postDetailsView.title }}</h1>
        {% endif %}
        <ul>
            <li>collezione: {% if postDetailsView.collection is not null %}{{ postDetailsView.collection.name }}{% else %}nessuna{% endif %}</li>
            <li>tag: {% if postDetailsView.tag is not null %}{{ postDetailsView.tag.name }}{% else %}nessuno{% endif %}</li>
        </ul>
    </header>
    <article id="post-details" style="display: none;"></article>
    <ul id="posts-list" style="display: block;">
    {% for post in postDetailsView.posts %}
        <li>
            {#<a href="/prodotti/dettaglio/{{ post.slug }}/">#}
            <a href="#" onclick="showPost({{ post.id }});">
                <figure>
                    {% media post.image, 'small' %}
                    <figcaption>{{ post.name }}</figcaption>
                </figure>
                <detail id="post-{{ post.id }}" style="display: none;">
                    <figure>
                        <img src="{% path post.image, "wide" %}" />
                    </figure>
                    <h1>{{ post.name }}</h1>
                    <h3>{% if postDetailsView.tag is not null %}{{ postDetailsView.tag.name }}{% endif %} {% if postDetailsView.collection is not null %}{{ postDetailsView.collection.name }}{% endif %}</h3>
                    <div class='description'>{{ post.description | markdown }}</div>
                </detail>
            </a>
                
            {# { post.rawDescription | markdown } #}
        </li>
    {% endfor %}
    </ul>
    <script>
        function backToPostDetail() {
            $('#posts-back-button').hide();
            $('#post-attachment-button').show();
            $('#post-details').hide();
            $('#posts-list').show(); 
            $('.posts-filter').children().show();
            $('#post-details').html( "" );
            $(document.body).removeClass('prodotti-dettaglio');
//            window.history.pushState('elenco-prodotti', 'Prodotti', '/../');
            return false;
        }
        function showPost(id) {
            $('#post-details').html( $('#post-'+id).html() );
            $('#posts-list').hide(); 
            $('.posts-filter').children().hide();
            $('#posts-back-button').show();
            $('#post-attachment-button').show();
            $('#post-details').show();
            $(document.body).addClass('prodotti-dettaglio');
//                window.history.pushState('dettaglio-prodotto', '{# { post.name }}', 'prodotti/{{ post.slug } #}');
            return false;
        }
        
        if ({% if app.request.get('p') %}true{% else %}false{% endif %}) {
            window.addEventListener('load', function() { showPost({{ app.request.get('p') }}); }, false )
        }
        
    </script>
{% endmacro %}


{% macro admin_post_details(postDetailsView) %}
    <div class="tag">
        Contenuto della news
    </div>
{% endmacro %}